# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='InstrBelongsName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='achievement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='beginDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='cname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='createDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='createUser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='ename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='eqid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='function',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='innerId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='instrBelongsType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='instrCategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='instrCategoryName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='instrSource',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='instrSupervise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='instrVersion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='instruType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='isshow',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='nation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='org',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='postalcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='requirement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='serviceContent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='serviceUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='shareMode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='technical',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='updateUser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='worth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='achievement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='amounts',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='applicant',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='applicantEmail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='applicantPhone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='applicantUnit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='cname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='codeCpd',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='comment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='contractNumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='county',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='declarationNumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='ename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='eqType',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='fee',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='feesApproved',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='function',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='hsCode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='importPort',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='innerId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='insCode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='instrBelongsName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='instrBelongsType',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='instrCategory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='instrSource',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='instrSupervise',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='instrVersion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='instruType',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='manufacturer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='nation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='numberCpd',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='postalCode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='province',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='record',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='requirement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='responsibleCustoms',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='serviceAmount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='serviceContent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='serviceUrl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='serviceWay',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='share',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='shareMode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='subjectArea',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='subjectContent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='subjectIncome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='subjectName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='technical',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xajtdx_instrument_test',
            name='worth',
            field=models.CharField(max_length=100),
        ),
    ]
