# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_xajtdx_instrument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xajtdx_instrument',
            old_name='type',
            new_name='eqType',
        ),
    ]
