# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_auto_20171017_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xajtdx_instrument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
