# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_auto_20171017_0951'),
        ('utility', '0003_auto_20170831_1630'),
    ]

    operations = [
    ]
