# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chdfh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.CharField(blank=True, max_length=128)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('occupation', models.CharField(blank=True, max_length=64)),
                ('reward', models.IntegerField(blank=True, default=0)),
                ('topic_count', models.IntegerField(blank=True, default=0)),
                ('post_count', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
