# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chdfh', '0003_auto_20180307_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='QQ',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
