# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-13 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chdfh', '0007_auto_20180313_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoholdetection',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (2, '饮酒'), (3, '醉酒')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='alcoholdetection',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(1, 'mg/100ml'), (2, 'mg/ml')], default=1, verbose_name='单位'),
        ),
    ]
