# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chdfh', '0009_auto_20180313_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoholdetection',
            name='jobnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chdfh.EmployeeInfo', verbose_name='雇员'),
        ),
    ]
