# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-15 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chdfh', '0011_auto_20180313_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='department',
            field=models.CharField(blank=True, max_length=32, verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='post',
            field=models.CharField(blank=True, max_length=32, verbose_name='岗位'),
        ),
    ]
