from django.db import models

# Create your models here.

class UserInfo(models.Model):
    user = models.CharField(max_length=32)
    pwd = models.CharField(max_length=32)

    def __unicode__(self):
        return self.user

class xajtdx_instrument_test(models.Model):
    id = models.DecimalField(primary_key=True,max_digits=10,decimal_places=0)
    instruType = models.CharField(max_length=100)
    achievement = models.CharField(max_length=100)
    cname = models.CharField(max_length=100)
    contact = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    establish = models.DateTimeField()
    fee = models.CharField(max_length=100)
    innerId = models.CharField(max_length=100)
    insCode = models.CharField(max_length=100)
    level = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    province = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    county = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    postalCode = models.CharField(max_length=100)
    requirement = models.CharField(max_length=100)
    serviceContent = models.CharField(max_length=100)
    serviceUrl = models.CharField(max_length=100)
    shareMode = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    eqType = models.CharField(max_length=100)
    url = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    beginDate = models.DateTimeField()
    ename = models.CharField(max_length=100)
    function = models.CharField(max_length=100)
    nation = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    technical = models.CharField(max_length=100)
    worth = models.CharField(max_length=100)
    instrBelongsType = models.CharField(max_length=100)
    instrBelongsName = models.CharField(max_length=100)
    instrCategory = models.CharField(max_length=100)
    instrSource = models.CharField(max_length=100)
    instrSupervise = models.CharField(max_length=100)
    instrVersion = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    codeCpd = models.CharField(max_length=100)
    numberCpd = models.CharField(max_length=100)
    declarationNumber = models.CharField(max_length=100)
    contractNumber = models.CharField(max_length=100)
    importPort = models.CharField(max_length=100)
    responsibleCustoms = models.CharField(max_length=100)
    importDate = models.DateTimeField()
    share = models.CharField(max_length=100)
    feesApproved = models.CharField(max_length=100)
    hsCode = models.CharField(max_length=100)
    record = models.CharField(max_length=100)
    amounts = models.CharField(max_length=100)
    serviceTime = models.DateTimeField()
    serviceWay = models.CharField(max_length=100)
    serviceAmount = models.CharField(max_length=100)
    subjectName = models.CharField(max_length=100)
    subjectIncome = models.CharField(max_length=100)
    subjectArea = models.CharField(max_length=100)
    subjectContent = models.CharField(max_length=100)
    applicant = models.CharField(max_length=100)
    applicantPhone = models.CharField(max_length=100)
    applicantEmail = models.CharField(max_length=100)
    applicantUnit = models.CharField(max_length=100)
    comment = models.CharField(max_length=100)

class xajtdx_instrument(models.Model):
    id = models.AutoField(primary_key=True)
    eqid = models.CharField(max_length=100,null=True,blank=True)
    instruType = models.CharField(max_length=100,null=True,blank=True)
    cname = models.CharField(max_length=200,null=True,blank=True)
    ename = models.CharField(max_length=200,null=True,blank=True)
    innerId = models.CharField(max_length=100,null=True,blank=True)
    instrBelongsType = models.CharField(max_length=100,null=True,blank=True)
    InstrBelongsName = models.CharField(max_length=100,null=True,blank=True)
    instrCategory = models.CharField(max_length=100,null=True,blank=True)
    instrCategoryName = models.CharField(max_length=100,null=True,blank=True)
    instrSource = models.CharField(max_length=100,null=True,blank=True)
    instrSupervise = models.CharField(max_length=100,null=True,blank=True)
    worth = models.CharField(max_length=100,null=True,blank=True)
    nation = models.CharField(max_length=100,null=True,blank=True)
    manufacturer = models.CharField(max_length=100,null=True,blank=True)
    beginDate = models.DateTimeField(null=True,blank=True)
    type = models.CharField(max_length=100,null=True,blank=True)
    instrVersion = models.CharField(max_length=100,null=True,blank=True)
    technical = models.CharField(max_length=100,null=True,blank=True)
    function = models.CharField(max_length=100,null=True,blank=True)
    subject = models.CharField(max_length=100,null=True,blank=True)
    serviceContent = models.CharField(max_length=100,null=True,blank=True)
    achievement = models.CharField(max_length=100,null=True,blank=True)
    status = models.CharField(max_length=100,null=True,blank=True)
    requirement = models.CharField(max_length=100,null=True,blank=True)
    fee = models.CharField(max_length=100,null=True,blank=True)
    serviceUrl = models.CharField(max_length=100,null=True,blank=True)
    street = models.CharField(max_length=100,null=True,blank=True)
    contact = models.CharField(max_length=100,null=True,blank=True)
    phone = models.CharField(max_length=100,null=True,blank=True)
    email = models.CharField(max_length=100,null=True,blank=True)
    address = models.CharField(max_length=100,null=True,blank=True)
    postalcode = models.CharField(max_length=100,null=True,blank=True)
    shareMode = models.CharField(max_length=100,null=True,blank=True)
    org = models.CharField(max_length=100,null=True,blank=True)
    image = models.CharField(max_length=100,null=True,blank=True)
    isshow = models.CharField(max_length=100,null=True,blank=True)
    createDate = models.DateTimeField(null=True,blank=True)
    createUser = models.CharField(max_length=100,null=True,blank=True)
    updateDate = models.DateTimeField(null=True,blank=True)
    updateUser = models.CharField(max_length=100,null=True,blank=True)

